"""empty message

Revision ID: 049b9555e2c0
Revises: 
Create Date: 2017-01-14 15:38:49.267021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049b9555e2c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('prefix_x', sa.String(), nullable=True),
    sa.Column('prefix_y', sa.String(), nullable=True),
    sa.Column('solution_at_x', sa.Float(), nullable=True),
    sa.Column('solution_at_y', sa.Float(), nullable=True),
    sa.Column('mi', sa.Float(), nullable=True),
    sa.Column('k', sa.Float(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_settings')
    # ### end Alembic commands ###
