"""empty message

Revision ID: 569f52d17697
Revises: 75d80bc3b8f5
Create Date: 2016-12-28 00:08:26.292214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569f52d17697'
down_revision = '75d80bc3b8f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('sample_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample', 'SampleType', ['sample_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'sample_type_id')
    # ### end Alembic commands ###
