"""empty message

Revision ID: 616149c05a78
Revises: fe9cc1edbe3f
Create Date: 2017-01-15 22:27:21.428328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616149c05a78'
down_revision = 'fe9cc1edbe3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_settings', sa.Column('r', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_settings', 'r')
    # ### end Alembic commands ###
