"""empty message

Revision ID: 75d80bc3b8f5
Revises: 5e4d8dbd1466
Create Date: 2016-12-28 00:01:21.705812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d80bc3b8f5'
down_revision = '5e4d8dbd1466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SampleType_sample_type_settings_id_fkey', 'SampleType', type_='foreignkey')
    op.drop_column('SampleType', 'sample_type_settings_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SampleType', sa.Column('sample_type_settings_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('SampleType_sample_type_settings_id_fkey', 'SampleType', 'SampleTypeSettings', ['sample_type_settings_id'], ['id'])
    # ### end Alembic commands ###
