"""empty message

Revision ID: 785c80de9e85
Revises: fa192afd0851
Create Date: 2016-12-28 00:27:01.384959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785c80de9e85'
down_revision = 'fa192afd0851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('SampleTypeSettings_sample_type_id_fkey', 'SampleTypeSettings', type_='foreignkey')
    op.drop_column('SampleTypeSettings', 'sample_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SampleTypeSettings', sa.Column('sample_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('SampleTypeSettings_sample_type_id_fkey', 'SampleTypeSettings', 'SampleType', ['sample_type_id'], ['id'])
    # ### end Alembic commands ###
