"""empty message

Revision ID: a10f19a3b460
Revises: e630dba991ff
Create Date: 2016-12-27 23:10:20.432000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10f19a3b460'
down_revision = 'e630dba991ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_type_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_type_settings_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sample_type_settings_id'], ['sample_type_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('datasample_type_settings')
    op.drop_table('datasample_type')
    op.add_column('datasample', sa.Column('sample_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'datasample', 'sample_type', ['sample_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasample', type_='foreignkey')
    op.drop_column('datasample', 'sample_type_id')
    op.create_table('datasample_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='datasample_type_pkey')
    )
    op.create_table('datasample_type_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='datasample_type_settings_pkey')
    )
    op.drop_table('sample_type')
    op.drop_table('sample_type_settings')
    # ### end Alembic commands ###
