"""empty message

Revision ID: ac71ff518f4b
Revises: 59fe1432bf07
Create Date: 2016-12-27 22:51:54.914366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac71ff518f4b'
down_revision = '59fe1432bf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasample_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('datasample', sa.Column('name', sa.String(), nullable=True))
    op.add_column('datasample', sa.Column('sample', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('datasample', 'url')
    op.drop_column('datasample', 'result_no_stop_words')
    op.drop_column('datasample', 'result_all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasample', sa.Column('result_all', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('datasample', sa.Column('result_no_stop_words', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('datasample', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('datasample', 'sample')
    op.drop_column('datasample', 'name')
    op.drop_table('datasample_type')
    # ### end Alembic commands ###
