"""empty message

Revision ID: ddb8ebdc4ee2
Revises: 616149c05a78
Create Date: 2017-01-15 22:47:31.424041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddb8ebdc4ee2'
down_revision = '616149c05a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_settings', sa.Column('mi_k', sa.Float(), nullable=False))
    op.alter_column('sample_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sample_settings', 'k')
    op.drop_column('sample_settings', 'mi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_settings', sa.Column('mi', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sample_settings', sa.Column('k', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('sample_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sample_settings', 'mi_k')
    # ### end Alembic commands ###
