"""empty message

Revision ID: fa192afd0851
Revises: 569f52d17697
Create Date: 2016-12-28 00:14:35.821834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa192afd0851'
down_revision = '569f52d17697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SampleTypeSettings', sa.Column('sample_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'SampleTypeSettings', 'SampleType', ['sample_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'SampleTypeSettings', type_='foreignkey')
    op.drop_column('SampleTypeSettings', 'sample_type_id')
    # ### end Alembic commands ###
