"""empty message

Revision ID: fe9cc1edbe3f
Revises: 9ca51e586a34
Create Date: 2017-01-15 18:20:57.610949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9cc1edbe3f'
down_revision = '9ca51e586a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_settings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_settings', 'flask_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample_settings', type_='foreignkey')
    op.drop_column('sample_settings', 'user_id')
    # ### end Alembic commands ###
